// <auto-generated />
namespace Test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class WorkoutDate_string_to_DateTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WorkoutDate_string_to_DateTime));
        
        string IMigrationMetadata.Id
        {
            get { return "202408082224483_WorkoutDate_string_to_DateTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
